# https://github.com/nimmis/docker-ubuntu


FROM ubuntu:14.04

MAINTAINER Stefan Schatz <stefan.schatz@osbg.at>

# disable interactive functions
ENV DEBIAN_FRONTEND noninteractive

# Do OS fixes
COPY bin/fix.sh /root/fix.sh
RUN /root/fix.sh && rm -f /root/fix.sh

# configure supervisor
COPY supervisor/supervisord.conf /etc/supervisor/
COPY supervisor/conf.d/crond.conf /etc/supervisor/conf.d/
COPY supervisor/conf.d/syslog-ng.conf /etc/supervisor/conf.d/

# Add my_init script and help scripts 
COPY bin/setuser /usr/local/bin/setuser
COPY bin/my_init /sbin/my_init
COPY bin/my_service /sbin/my_service

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["/sbin/my_init"]


