# https://github.com/nimmis/docker-ubuntu


FROM ubuntu:15.10

MAINTAINER Stefan Schatz <stefan.schatz@osbg.at>

# disable interactive functions
ENV DEBIAN_FRONTEND noninteractive
ENV HOME /root

# Do OS fixes
COPY prepareUbuntu.sh /root/prepareUbuntu.sh
RUN /root/prepareUbuntu.sh && rm -f /root/prepareUbuntu.sh

# configure supervisor
COPY supervisor/ /etc/supervisor/
#COPY supervisor/supervisord.conf /etc/supervisor/
#COPY supervisor/conf.d/crond.conf /etc/supervisor/conf.d/
#COPY supervisor/conf.d/syslog-ng.conf /etc/supervisor/conf.d/

# Add my_init script and help scripts 
COPY bin/ /sbin/
#COPY bin/setuser /usr/local/bin/setuser
#COPY bin/my_init /sbin/my_init
#COPY bin/my_service /sbin/my_service

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["/sbin/my_init"]


